name: "lotterySite"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "2020-07-14"
machine_id: 1

auth:
  expiration_time: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: localhost 
  port: 3306
  user: "root"
  password: "jh790613"
  dbname: "lottery"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: localhost
  port: 6379
  password: "jh790613"
  db: 0
  pool_size: 100